[project]
name = "custom_tool"
version = "0.1.0"
description = "custom-tool using crewAI"
authors = [{ name = "Your Name", email = "you@example.com" }]
requires-python = ">=3.10,<3.13"
dependencies = [
    "crewai[tools]>=0.108.0,<1.0.0"
]

[project.scripts]
custom_tool = "custom_tool.main:run"
run_crew = "custom_tool.main:run"
train = "custom_tool.main:train"
replay = "custom_tool.main:replay"
test = "custom_tool.main:test"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.crewai]
type = "crew"
